- src/components/input/Input.tsx
- src/components/loading/Loading.tsx
main 브랜치에서 발생하는 import 에러 해결
-
-
-
-
-
> import 에러 해결

- src/Router.tsx
- src/components/alert/CustomAlert.tsx
- src/components/alert/index.ts
- src/components/loading/Loading.tsx
- src/pages/page404/Cute404.tsx
- src/pages/page404/Page404.tsx
- 사용자의 잘못된 경로 접근 시 보여줄 404 페이지 작업
- 404 페이지에 애니메이션을 추가한 cute 404 페이지 작업
- router에 404페이지 추가
- alert 용도로 사용할 CustomAlert 컴포넌트 작업
- router에 404 페이지 추가
- 기본 404 페이지와 cute 404 페이지 추가
- CustomAlert 컴포넌트 작업
- 언젠가는 만들어야 하는 404 페이지를 만들어봤어요! 디자인 괜찮나요?!
- page404.tsx는 커스텀 404 페이지를 제작해야 할 상황이 발생할 경우에 사용하기 위해서 남겨뒀어요!
- 만약 cute404페이지만 사용하게 된다면 컴포넌트명을 바꿔도 될 것 같아요 :)
-
**cute404 페이지 ,귀엽죠?**
> 404 에러 페이지 작업

- src/pages/home/Home.tsx
- #20 번 이슈 해결!
- Home.tsx에서 'Create set' 버튼을 클릭했을 때 스택이 아무것도 선택되지 않았다면 이벤트가 발생하지 않도록 처리했습니다. 
- 이 경우에 alert나 toast 등으로 1개 이상 선택해야 한다고 알려주는게 좋을까요?
-  
-
> fix: 스택이 아무것도 선택되지 않았을 때 깜빡임 해결

- src/pages/page404/Cute404.tsx
- 404 페이지에서 뒤로 가는 버튼 추가
- 404 페이지에서 메인 홈으로 가는 버튼 추가
-
-
-
-
-
> 404 페이지에서 뒤로 가는 버튼 & home으로 가는 버튼 추가

- src/pages/result/Result.tsx
- result page의 css 작업 진행
- copy url 버튼을 누르면 이미지의 url이 저장된다
- mainpage로  바로 이동할 수 있는 버튼 추가
-
-
-
-
-
> result page의 CSS와 url 저장 버튼 작업

- src/components/header/Header.tsx
- src/components/loading/Loading.tsx
- src/constants/animations.ts
로딩창 애니메이션 
- 로딩창 애니메이션
- ⭐️ 헤더 둥글기 제거 ⭐️
-
-   [여기꺼 가져왔습니다](https://codepen.io/imathis/pen/ZYEWrw)
-
> feat: 로딩창 애니메이션 추가

- src/components/header/Header.tsx
- src/constants/constants.ts
- src/pages/result/Result.tsx
- result 페이지에 stackticon 타이틀 띄우기
- Stackticon을 constants의 APP_NAME으로 만들었습니다
-
-
-
-
> result 페이지에 stackticon 타이틀 띄우기

- src/pages/home/Home.tsx
setButtonClicked(true) 를 버튼이 눌리기만 하면 true로 바꾸는 것이 아닌
stack이 있을 때 버튼을 누른 경우에만 true로 동작하게 함
close #38 
-
-
-
-
-
> hotfix: stack을 선택하지 않고 버튼을 누른 후, stack을 선택하고 눌러도 버튼이 작동하지 않는 이슈 해결

- package.json
- src/App.tsx
- src/services/google-analytics/GoogleAnalyticsTracker.tsx
- yarn.lock
라우터 설정을 리액트 라우터 v6 권장사항에 따라 변경했습니다.
- App.tsx의 `HashRouter` -> `RouterProvider`
- 
-
-
-   [create-hash-router](https://reactrouter.com/en/main/routers/create-hash-router)
-
> change router settings in accordance with react-router-v6 recommandation

- src/components/loading/Loading.tsx
close #57 
- add overflow-y in loading page container
- Unable to scroll on loading page
-
-
-
> stacks image appears on the loading page

- src/pages/background-colors/BackgroundColors.tsx
- change BackgroundColors.tsx Style
- close #60 
- Change border into outline
- Change Typography fontWeight into bold
- How about this design? 
-
before
after
> Change BackgroundColors page Design and fix issue #60

- src/components/guides/GuideSample.tsx
- src/components/guides/GuideUsage.tsx
- src/components/guides/index.ts
- src/components/landing/Landing.tsx
- src/components/landing/index.ts
- src/constants/icons.tsx
- src/pages/home/Home.tsx
refactored home
- separate components from `pages > home`
- separate icons from home into `constants > icons`
- changed all tags into MUI components
- plz deploy after all refactorings are done
-
> refactoring : home

- .github/workflows/deploy.yml
- vite.config.ts
set base publishing path in vite.config.ts
set pipeline for changing deploy folder
> fix: change publishing folder with github actions

- .github/workflows/deploy.yml
> fix: add env variables in pipeline

- .github/auto_assign_reviewer.yml
- .github/workflows/auto_assign.yml
created yml files for add reviewers and assignees automatically
> feat: auto assign reviewers and assignees

- .github/auto_assign_reviewer.yml
- .github/workflows/auto_assign.yml
- README.md
- src/components/input/Input.tsx
- src/components/read-repository/ReadRepository.tsx
- src/types/packageJson.ts
- src/utils/extractStacks.ts
- src/utils/test/extractStacks.test.ts
fix auto assignments
trigger action when pull request is (opened/reopened/ready_for_review)
> fix auto assignments

- src/components/input/Input.tsx
- src/components/read-repository/ReadRepository.tsx
- src/types/packageJson.ts
- src/utils/extractStacks.ts
- src/utils/test/extractStacks.test.ts
refactor functions in `extractStacks`, `read-repo`
- seperate functions that "make elements in array unique with `set`"
- add test with new function
- resolved with issue about warning when add skills with read-repository
- add type for `package.json`
> refactoring functions with read github repository

- .eslintignore
- .eslintrc.json
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/new_feature.md
- .github/workflows/auto_assign.yml
- .husky/pre-commit
- .husky/pre-push
- package.json
- yarn.lock
add git hooks
- fixed yml files related to auto assignments 
- add git hooks with husky
> 1. check `lint`, `ts`, `test` before commit
> 2. build project before push
> 3. prevent directly push to main branch
> add git hooks

- .prettierignore
- src/Router.tsx
- src/RouterContainer.tsx
- src/components/button-options/ButtonOptions.tsx
- src/components/header/Header.tsx
- src/components/loading-alter/index.ts
- src/components/loading/BlockLoading.tsx
- src/components/loading/LogoLoading.tsx
- src/components/loading/index.ts
- src/components/stack-container/StackContainer.tsx
- src/components/stack-group/StackGroup.tsx
- src/components/stack-group/index.ts
- src/components/stacks/index.ts
- src/hooks/useIntersectionObserver.ts
- src/pages/background-colors/BackgroundColors.tsx
- src/pages/result/bottom-buttons/BottomButtons.tsx
- src/types/location.ts
close #92 
Refactor components
- add types: deleted all any types
- changed component name : Stacks -> StackGroup
- merged to loading components into Loading folder, and renamed them `LogoLoading`, `BlockLoading`
> Refactor components

- .vscode/settings.json
- package-lock.json
- package.json
- src/components/button-options/ButtonOptions.tsx
- src/components/toast/Toast.tsx
- src/components/toast/index.ts
- src/constants/constants.ts
- src/pages/result/Result.tsx
- src/pages/result/bottom-buttons/BottomButtons.tsx
- src/types/common.ts
- src/types/toast.ts
create `Toast.tsx` to show toast message instead of previous window.alert
- created `Toast.tsx` 
- refactored buttonOptions component : made function lighter and seperate functions
> show toast message and remove window.alert

- CONTRIBUTING.md
- README.md
add contribution guide on `CONTRIBUTING.md`
> docs: add contribution guide on CONTRIBUTING.md

- package.json
- patches/html-to-image+1.11.11.patch
- src/utils/imageConverter.ts
- yarn.lock
- close #64 
- Modifying html-to-image directly using patch-packages
- Confirmed that the image is created in a fixed size regardless of the device
- Add patch-packages
- If the html-to-image image size bug is fixed, patch-packages may be removed.
> FIX: Resolved a bug where images are not fixed depending on the device

- package.json
- yarn.lock
- upgrade simple-icon library to update icons (`8.5.0` -> `13.18.0`)
-
-
-
- [link name](url)
-
> chore: update simple-icons lib

- package.json
> chore: build 1.3.0

- .vscode/settings.json
- index.html
added meta tag to verify ownership of page and review
-
-
-
-
- [link name](url)
-
> Add ads with google adsense

- .vscode/settings.json
- index.html
This reverts commit 549f81fb87c339f915ea9c727d770ba7051e72a3, reversing changes made to d41477d4c1c8671c85df7801c5ae02cdd8adf5cb.
-
-
-
-
- [link name](url)
-
> Revert "Merge pull request #149 from msdio/feature/add-ad"

- index.html
add script on index.html head to verify page owner
-
-
-
-
- [link name](url)
-
> feat: add script to verify google adsense

- .github/workflows/deploy.yml
- .vscode/settings.json
change version of `actions/upload-pages-artifact` into v3
> chore: change version of action
